### ISSUE TITLE
Parts from the website should be named

### ISSUE THREAD

**Issue by RatchetOfVaporex** [virtual-vgo/vvgo#105]
When downloading parts, the file names are just random characters; perhaps we could make them file names that coincide with the parts, something like this?

**[PROJECT NAME] - [INSTRUMENT NAME]**

examples:
**Proof of a Hero - Alto Saxophone 1**
**Snake Eater - Shaker**

**Comment by 0az** [comment]
If I'm not mistaken, there's a HTTP header that lets you set this.

Assigning to @noloerino for now.

**Comment by noloerino** [comment]
I think you're right that `Content-Disposition` lets you set a suggested filename, but after looking into a bit it seems it's not so simple:
1. The actual resource itself is hosted on DigitalOcean, but we can set headers for individual files on upload (https://www.digitalocean.com/docs/spaces/how-to/set-file-metadata/) - implementing this would require a change on our upload endpoints + adding the field to already-uploaded data for the current project.
2. If we set it to have `attachment; filename=<name>` as suggested, then the browser will download the file rather than displaying it within the browser's PDF behavior ([MDN link](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition)), which I think isn't the behavior we want. After a bit of Googling, I think the only way to set the name of the file on download is by setting the name of the file when it's uploaded to DO.

**Comment by jacksonargo** [comment]
The files are named using their md5sum, which is convenient since it protects from duplicate file names. But we can also just do something like: `[PROJECT NAME] - [INSTRUMENT NAME] - [MD5SUM]`

**Comment by jacksonargo** [comment]
Multiple parts can point to the same music sheet or click track. Like, trumpet 1 and trumpet 2 might both be the same file. So, if we _do_ use files names from object storage... then someone might get confused why they are downloading a part for trumpet 1 when they clicked the link for trumpet 2.

**Comment by noloerino** [comment]
> The files are named using their md5sum, which is convenient since it protects from duplicate file names. But we can also just do something like: [PROJECT NAME] - [INSTRUMENT NAME] - [MD5SUM]

This seems a little less than ideal because we end up with an md5 in the filename anyway, although at least people can tell what parts they're downloading. This would still require renaming all the files in the current project if we want to implement it though.

> Multiple parts can point to the same music sheet or click track. Like, trumpet 1 and trumpet 2 might both be the same file. So, if we do use files names from object storage... then someone might get confused why they are downloading a part for trumpet 1 when they clicked the link for trumpet 2.

Wouldn't we just name them by whatever name they were uploaded by, e.g. "PoH - Trumpet Clix.mp3" for both?

**Comment by jacksonargo** [comment]
`PoH - Trumpet Clix - [MD5SUM].mp3` would work.

**Comment by jacksonargo** [comment]
> This would still require renaming all the files in the current project if we want to implement it though.

I don't think that will be a big deal.

**Comment by RatchetOfVaporex** [comment]
> This seems a little less than ideal because we end up with an md5 in the filename anyway, although at least people can tell what parts they're downloading. This would still require renaming all the files in the current project if we want to implement it though.

Why is the MD5SUM necessary in naming the files? I'm just curious.

> PoH - Trumpet Clix [MD5SUM].mp3 would work.

Small Pedantic Thing, but I'd spell out the project file with the full name:
`Proof of A Hero - Trumpet 1 CLIX [MD5SUM].mp3` for example.

**Comment by jacksonargo** [comment]
The md5sum is necessary so that we can track revisions to the parts. If someone uploads a new file, it will always get a unique file name.

**Comment by RatchetOfVaporex** [comment]
Sorry, I just edited this, but can we put a check that ensures that files with duplicate names aren't uploaded?

**Comment by jacksonargo** [comment]
We upload revisions and fixes to the existing parts, so if someone tries to upload a new file with the same name as an existing file, that's perfectly :ok_hand:

**Comment by jacksonargo** [comment]
We're no longer renaming the files, so this is not an issue.
