### ISSUE TITLE
Part Request Form

### ISSUE THREAD

**Issue by RatchetOfVaporex** [virtual-vgo/vvgo#214]
It would be really helpful at the bottom of each part page to have a part request form for instruments if they want to play something but they don't see it. My thinking is that it would link to a google form where people could input things, and we would update the form periodically depending on which pieces are currently viewable to the public.

**Comment by Ranzha** [comment]
Given the current channels for Teams applications and arrangement submissions, this doesn't seem hard to do.

Instead of having a part request GForm per piece, we could do one all-encompassing one, and have respondents select which piece applies to their request from a dropdown.

I feel like this shouldn't necessarily live on /parts, but rather on Discord in the pins in each Current Project channel.

**Comment by jacksonargo** [comment]
Ya if yall wanna make the form, I can make the Captain Hook script for it.

**Comment by RatchetOfVaporex** [comment]
> 
> 
> Given the current channels for Teams applications and arrangement submissions, this doesn't seem hard to do.
> 
> Instead of having a part request GForm per piece, we could do one all-encompassing one, and have respondents select which piece applies to their request from a dropdown.
> 
> I feel like this shouldn't necessarily live on /parts, but rather on Discord in the pins in each Current Project channel.

Good idea. I think this is the better place for it. I'll close this issue and we can go from there.
